Enable CEPH mgr prometheus module
vexxhost/ansible-collection-ceph pull request #39
Opened 2024-07-16 05:33 UTC by yaguangtang

Fixes #38

2024-07-16 12:25 UTC, yaguangtang commented
recheck

2024-07-16 12:44 UTC, mnaser approved these changes

2024-07-16 17:19 UTC, mnaser requested changes

2024-07-16 17:19 UTC, mnaser commented on roles/mgr/tasks/main.yml
> +  changed_when: result.rc == 0
This should probably be false, it probably returns 0 all the time so it will always say changed.

2024-07-17 06:38 UTC, yaguangtang commented
recheck

2024-07-17 09:09 UTC, yaguangtang commented on roles/mgr/tasks/main.yml
> +  changed_when: result.rc == 0
updated

2024-07-17 13:35 UTC, merged